### PR TITLE
Phase 2.2 Implement fiber version of warp

### PR DESCRIPTION
**Pull request by ouromoros**
This pull request is created for tracking the progress in implementing fiber version of warp. The idea is to first change the imports and then deal with the details step by step. Changes are expected to be made in all parts related with network IO. The result would be an implementation of warp using light-weight fibers thread.

### CODE REVIEW

**Comment by ouromoros** [comment]
It appears that adapting warp to use fiber isn't as trivial as making a patch to it. The main problems are with the Exception handling and Fiber/IO conversion code.

Due to the exception handling code, I have to use `fiber` and `liftIO` virtually every where to make it just typecheck. This is a bit tiresome and not very appealing work. Also it makes the code complicated.

I'll continue try to make ;it type check though. There shouldn't be much problem after taht.

**Comment by ouromoros** [comment]
I seem to have left out http2 support when working with `Network` library. Now I would just also comment out `HTTP2.hs` and maybe look back when I'm finished.

**Comment by ouromoros** [comment]
A lot of the code doesn't really have anything to do with threads or network IO. I could have left them unchanged and only do necessary modifications or just change every function type to use `Fiber`. I've preferred the latter one just for convenience. There should be much difference practically.

**Comment by ouromoros** [comment]
Well, there is one major problem. `TimeoutManager` in `Warp` uses `killThread`, which involves asynchrous exception. I read the source code and it definitely can't be used on fiber threads directly. I'm not quite sure how it can be done now...

**Comment by rahulmutt** [comment]
@ouromoros For this evaluation I think it's ok to do a simple liftIO for kill thread. Asynchronous exceptions should work on fiber TSOs, it's just that the fiber throwing the async exception will be blocked until the other TSO confirms that it has received it. We could make that bit non-blocking, but I don't think it's a huge deal at this point. We can make non-blocking implementation of `killThread` a target of the next evaluation.

**Comment by rahulmutt** [comment]
The main thing that has to be non-blocking in a web server are the IO operations since those are what have the long wait times. The blocking time of throwing an asynchronous exception, on the other hand, is very little relative to amount of time spent waiting for IO.

**Comment by ouromoros** [comment]
@rahulmutt That looks quite convincing to me, thanks. After checking the source again I realize it does indeed work on fiber TSOs. Don't know what I was thinking about.  I should probably read more carefully next time.

**Comment by ouromoros** [comment]
I've finally made the code pass type check and compile, though it's still not time to test it yet. There are a couple of more things to do.

- Some functions like `bindRandomTCPPort` and `fdSocket` were not implemented and should be added to `fibers-network` package. Currently I just use a placeholder for these functions.

- The code is a little messed with `Fiber` and `IO` types. We're using `fiber` and `liftIO` everywhere and especially around exception handling codes like `bracket` and `finally`. Since exception handling part in Fiber is not available yet, perhaps I can only tidy them up a bit.

**Comment by ouromoros** [comment]
I noticed the use of `Control.Concurrent.STM` and spent some time reading about it. They can be blocking in numerous ways, so there might be the need of implementing fiber version of `retry`.

**Pull request merged**
