### PR TITLE
first commit code

### PR DESCRIPTION
**Pull request by ouromoros**
I've done some work based on how my mentor and I discussed in emails, about implementing Network IO for FIber.

I've set up the library as it is. *Many* things ( library structure, license, code organization ) will probably need to be changed later. But I'll leave them this way for now.

`Network.hs` (probably complete) contains the functions that I have recognized to be used in Warp source code, and they all need to be adapted to use Fiber Monad. `Internal.hs` (incomplete) contains the functions that won't be used directly by Warp but are needed for IO anyway.

For functions like `c_accept`, `c_connect` I simply import them and use `liftIO` as a wrapper so they work with Fiber monad. The same goes for `threadWaitAccept` and `threadWaitConnect`, which only needs to call the runtime functions and yield automatically, leave work like polling to the runtime system.

I've written the code for `accept` and `connect` since they are relatively easy to implement, for they don't need to interact with buffer. Just want to make sure if I'm on the right track.

### CODE REVIEW

**Comment by ouromoros** [comment]
So far I have played with the cabal config file, restructured the project and made the project look good. I would try to compile it after adding imports to `Network.hs`. I would try to adapt some functions using the following code and get it pass code check first:
```haskell
io :: Fiber a -> IO a
io (Fiber a) = IO a
```
If this approach turns to be bad. I would end up having to rewrite every function that has argument like `a -> IO b` by hand. That's just a little annoying and won't be more difficult though.

One thing to mention is that it's probably not a good idea to put all these functions together just because they are all used by *Warp*. But just for simplicity, I'll keep them this way unless there is much spare time at the end.

**Comment by ouromoros** [comment]
The problem now is that since `Socket` is changed to use the Fiber version `MVar`, every function related to `Socket` need to be rewritten. That will be a lot of code being copied and there seems no other way around...

**Comment by ouromoros** [comment]
I felt not so well about copy/pasting code and thought about why I can't import **unexported** functions. I'm soon convinced that there's no guarantee thoses functions will have the same API or exist at all after small version update, so even if I can forcely import them there is little point in doing so.

Good news is I should be able to finish writing and testing the library next week. *Unless* something goes wrong during testing...

**Comment by ouromoros** [comment]
The code now compiles, so now I need only to take care of a few unimplemented code before actually testing it. So far very well.

Now the remaining work is to add more functions (`recv`, `sendTo` etc.) and arange exports. The code also need to be reorganized, but I'll put that off until we get a working demo.

**Comment by ouromoros** [comment]
It's almost done now. There's something with the `wait*` functions. A context need to be passed and I suppose it should be like what is done in `eta-fibers-dev`. Hopefully I'll finish that and all will be well tomorrow.

**Comment by ouromoros** [comment]
Everything so far seems to work now. And I've written a *HelloWorld* program that works to some extent. However, there seems to be some problem between the Scheduler mechanism and the Selector behavior now.

Suppose we have an `accept` loop, which accept a new connection, do something with it (e.g. spawn a new thread), then immediately accept again.

With the current approach, after the first `accept` the program would register the `Channel` and go into a **blockedloop**, then when a new connection comes, *inside* the loop, the Selector would pick the thread and try to run it.
```java
                    if (selectedKeys > 0) {
                        Iterator<SelectionKey> it = globalSelector.selectedKeys().iterator();
                        while (it.hasNext()) {
                            SelectionKey key = it.next();
                            if (key.isValid() && ((key.readyOps() & key.interestOps()) != 0)) {
                                TSO tso = (TSO) key.attachment();
                                key.cancel();
                                cap.tryWakeupThread(tso);
                            }
                            it.remove();
                        }
                    }
```
The key is canceled and the thread is woken up immediately after it. However, in Java NIO when `cancel` is called, the key is not actually canceled until the next `select`. At this time when we try to register the `Channel` again, the last `SelectionKey` isn't actually canceled, and a `CancelledKeyException` would be thrown and we're doomed.

Two solutions are present:
1. Just add a line after `selectNow` after the `key.cancel`. This is potentially slow.
2. Cancel all the keys at one time and call `selectNow` once after that. Only then do we deal with the threads attached to the key. (Add them to a global run queue perhaps) This might cost some space.

---

Well, it seems that the first approach doesn't work since it modifies the keys being iterated. So maybe we have to resort to the second approach.

**Comment by ouromoros** [comment]
Well, I've made some change to the scheduling code as below. 

```
                   while (selectedKeys > 0) {
                        LinkedList<TSO> tsoList = new LinkedList<>();
                        Iterator<SelectionKey> it = globalSelector.selectedKeys().iterator();
                        while (it.hasNext()) {
                            SelectionKey key = it.next();
                            if (key.isValid() && ((key.readyOps() & key.interestOps()) != 0)) {
                                TSO tso = (TSO) key.attachment();
                                key.cancel();
                                // cap.tryWakeupThread(tso);
                                tsoList.add(tso);
                            }
                            it.remove();
                        }
                        selectedKeys = globalSelector.selectNow();
                        for(TSO tso : tsoList){
                            cap.tryWakeupThread(tso);
                        }
                    }
```

Now the code almost works, though there are some concurrency problems. The socket would throw `java.nio.channels.ClosedByInterruptException` which I suppose is due to being interrupted somewhere. When I change `forkFiber` to just use `fiber` everything seems fine though.

I'll look into this in following days.

**Comment by ouromoros** [comment]
Well, I thought better and reimplemented `threadWait*` methods, but still not sure of the correctness of it. Also I had to change `checkforReadyIO` to use `pushToGlobalRunQueue` with a check, since after the fiber `block`, `TSO` seems to be detached from capability and `tryWakeupThread` would throw `NullPointerException`.
Here's the code in `checkForReadyIO`:
```java
                    while (selectedKeys > 0) {
                        Iterator<SelectionKey> it = globalSelector.selectedKeys().iterator();
                        while (it.hasNext()) {
                            SelectionKey key = it.next();
                            if (key.isValid() && ((key.readyOps() & key.interestOps()) != 0)) {
                                TSO tso = (TSO) key.attachment();
                                key.cancel();
                                if(tso.cap==null){
                                    pushToGlobalRunQueue(tso);
                                }
                                else{
                                    cap.tryWakeupThread(tso);
                                }
                            }
                            it.remove();
                        }
                        selectedKeys = globalSelector.selectNow();
                    }
```

**Comment by agocorona** [comment]
Hi @ouromoros  this supposes a change request to  eta/runtime/concurrent.  I can not figure out if that change is right or not.  @rahulmutt can you take a look at it?

**Comment by rahulmutt** [comment]
@ouromoros The change & the reasoning for it look sound to me. What you can do is fork the `typelead/eta` repo and work off a branch where you add your runtime changes. Once you have made all the necessary changes and this repo is working as intended, you can submit a PR to the upstream repo.

A quick way to rebuild just the runtime system is using `eta-build rts-clean`.

**Comment by ouromoros** [comment]
I'm merging it since this phase is done. Work during phase 2 can be checked in https://github.com/ouromoros/eta-gsoc/pull/2

**Pull request merged**
